# Generated by Django 4.2.23 on 2025-06-25 18:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Principal amount"
                    ),
                ),
                (
                    "interest_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annualized interest rate",
                        max_digits=5,
                        verbose_name="Interest rate (%)",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(
                        help_text="Total tenure in months", verbose_name="Term (months)"
                    ),
                ),
                (
                    "emi_cycle",
                    models.CharField(
                        choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                        default="MONTHLY",
                        max_length=10,
                        verbose_name="EMI cycle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("PAID", "Paid"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "late_fee_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of overdue amount per period",
                        max_digits=5,
                        null=True,
                        verbose_name="Late fee (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
            ],
            options={
                "verbose_name": "loan",
                "verbose_name_plural": "loans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Paid at"
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("due_date", models.DateField(verbose_name="Due date")),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount due"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Amount paid",
                    ),
                ),
                (
                    "interest_component",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Portion of amount_due that is interest",
                        max_digits=14,
                        verbose_name="Interest component",
                    ),
                ),
                (
                    "late_fee_accrued",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Late fee accrued",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DUE", "Due"), ("PAID", "Paid"), ("LATE", "Late")],
                        default="DUE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "repayment schedule",
                "verbose_name_plural": "repayment schedules",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOAN_DISBURSEMENT", "Loan Disbursement"),
                            ("REPAYMENT", "Repayment"),
                            ("LATE_FEE", "Late Fee"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "related_id",
                    models.CharField(max_length=36, verbose_name="Related ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
