# Generated by Django 4.2.23 on 2025-06-25 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="from_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="From user",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To user",
            ),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayment_schedules",
                to="loans.loan",
                verbose_name="Loan",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_payments",
                to="loans.loan",
                verbose_name="Loan",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Payer",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_as_borrower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Borrower",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="lender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_as_lender",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lender",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["to_user", "created_at"], name="loans_trans_to_user_05657d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repaymentschedule",
            index=models.Index(
                fields=["loan", "due_date"], name="loans_repay_loan_id_c6e76a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["loan"], name="loans_payme_loan_id_35d8fe_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["lender"], name="loans_loan_lender__e05194_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["borrower"], name="loans_loan_borrowe_4ce53f_idx"
            ),
        ),
    ]
