# Generated by Django 4.2.23 on 2025-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_LENDER", "Pending Lender Approval"),
                    ("PENDING_BORROWER", "Pending Borrower Approval"),
                    ("ACTIVE", "Active"),
                    ("PAID", "Paid"),
                    ("DEFAULTED", "Defaulted"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
