# Generated by Django 4.2.23 on 2025-07-05 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0003_alter_loan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("PAID", "Paid"),
                    ("DEFAULTED", "Defaulted"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
