# Generated by Django 4.2.23 on 2025-07-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_loan_created_by_alter_loan_status"),
    ]

    operations = []
