# Generated by Django 4.2.23 on 2025-07-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_add_created_by_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repaymentschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("DUE", "Due"),
                    ("PENDING_CONFIRMATION", "Pending Confirmation"),
                    ("PAID", "Paid"),
                    ("LATE", "Late"),
                ],
                default="DUE",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
