# Generated by Django 4.2.23 on 2025-06-25 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Body")),
                ("is_read", models.BooleanField(default=False, verbose_name="Is read")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="loans.loan",
                        verbose_name="Loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebSocketNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOAN_CREATED", "Loan Created"),
                            ("LOAN_ACCEPTED", "Loan Accepted"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("PAYMENT_DUE", "Payment Due"),
                            ("PAYMENT_OVERDUE", "Payment Overdue"),
                            ("LOAN_COMPLETED", "Loan Completed"),
                            ("CUSTOM_MESSAGE", "Custom Message"),
                        ],
                        default="CUSTOM_MESSAGE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Data"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is sent")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websocket_notification",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "websocket notification",
                "verbose_name_plural": "websocket notifications",
                "ordering": ["-notification__created_at"],
            },
        ),
    ]
